baseURL = 'https://highstake.tech/'
languageCode = 'en-us'
title = 'ğŸ HIGH/STAKE ğŸ¥© Nodes - powered by Nexus Informatik'
theme = 'greyscale'
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"

[params]
    # Provide some metadata for search and indexing services
    description = "Blockchain nodes and validators with focus on substrate based nodes."

[Author]
    name = "Nexus Informatik Durrer"
    email = "highstake@nexus-informatik.ch"

[blackfriday]
  hrefTargetBlank = true
